name: 01 - Building blocks

on: push

jobs:
    echo-sam:
        runs-on: ubuntu-latest
        steps:
            - name: hello world
              run: echo "hello there"
    echo-exit:
        runs-on: ubuntu-latest
        steps:
            - name: sucessful step
              run: |
                echo "bye there"
                exit 0
            - name: say goodbye
              run: echo "goodbye"
