name: 02 - Workflow Events

on: 
  push:
  pull_request:
  #commetned cron job as it triggers job every 5 min"
  #schedule:
  #  - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  echo-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: show the trigger
        run:  |
          echo "Event name: ${{ github.event_name }}"
    
        