name: using actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 04-using-actions/react-app
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: printing folder structure
              run: ls
            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: install dependecies
              run: npm ci
              working-directory: 04-using-actions/react-app
        # below example takes working directory from default section of run given in builds
            - name: run unit tests
              run: npm run test

        # checkout code from repo
        # install dependencies for react app
        # execute automated tasks

