name: 05 - 2 - Event Filters and Activity Types

on: workflow_dispatch
#    pull_request:
#        types: closed
#        branches: main
jobs:
    echo-pr:
        runs-on: ubuntu-latest
        steps:
            - name: pr event when closed
              run : |
                echo "Running whenever a PR is closed"